### ISSUE TITLE
luminus-undertow 0.1.8 failed

### ISSUE THREAD

**Issue by vinurs** [luminus-framework/luminus-undertow#1]
i update luminus-undertow to 0.1.8. and start the server, 
![image](https://user-images.githubusercontent.com/37489300/108576235-cc305280-7357-11eb-901e-7f222fefad67.png)

**Comment by yogthos** [comment]
Yup, that's a known issue due to [this bug](https://github.com/luminus-framework/ring-undertow-adapter/issues/13) in the undertow adapter.

**Comment by nikolap** [comment]
Just pushed a fix to the session middleware in the undertow adapter. Does 0.1.9 work for you?

**Comment by nikolap** [comment]
Apologies... try 0.1.10... just pushed up some more changes for session management

**Comment by vinurs** [comment]
thanks，ok now
